{
  "openapi": "3.0.3",
  "info": {
    "title": "Finance App API",
    "version": "0.0.1"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Development server"
    }
  ],
  "paths": {
    "/users/signup": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Create a new user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "required": true
                  },
                  "email": {
                    "type": "string",
                    "required": true
                  },
                  "password": {
                    "type": "string",
                    "required": true
                  }
                },
                "example": {
                  "name": "John Doe",
                  "email": "exapmle@example.com",
                  "password": "examplepassword"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "email": {
                          "type": "string"
                        },
                        "balance": {
                          "type": "integer"
                        }
                      }
                    }
                  },
                  "example": {
                    "data": {
                      "email": "useremail@example.com",
                      "balance": 40
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "validation error message"
                  }
                }
              }
            }
          },
          "409": {
            "description": "Email in use"
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Login",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "required": true
                  },
                  "password": {
                    "type": "string",
                    "required": true
                  }
                },
                "example": {
                  "email": "exapmle@example.com",
                  "password": "examplepassword"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User logged in",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "token": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "example": {
                    "data": {
                      "token": "exampletoken",
                      "email": "example@example.com",
                      "name": "examplename"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "validation error message"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/users/logout": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Logout",
        "parameters": [
          {
            "name": "Authorization",
            "description": "Token issued to a current user",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "User logged out"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get current user",
        "parameters": [
          {
            "name": "Authorization",
            "description": "Token issued to a current user",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Current user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "balance": {
                          "type": "integer"
                        }
                      }
                    }
                  },
                  "example": {
                    "data": {
                      "name": "exapmlename",
                      "email": "example@example.com",
                      "balance": 900
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/transactions": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "Get all user's transactions",
        "parameters": [
          {
            "name": "Authorization",
            "description": "Token issued to a current user",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "An array of user's transactions",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "properties": {
                        "transaction": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "string"
                            },
                            "date": {
                              "type": "object",
                              "day": {
                                "type": "number",
                                "minimum": 1,
                                "maximum": 31
                              },
                              "month": {
                                "type": "string",
                                "enum": [
                                  "january",
                                  "february",
                                  "march",
                                  "april",
                                  "may",
                                  "june",
                                  "july",
                                  "august",
                                  "september",
                                  "october",
                                  "november",
                                  "december"
                                ]
                              },
                              "year": {
                                "type": "number",
                                "minimum": 1900
                              }
                            },
                            "transactionType": {
                              "type": "string"
                            },
                            "category": {
                              "type": "string"
                            },
                            "comment": {
                              "type": "string"
                            },
                            "amount": {
                              "type": "integer"
                            },
                            "balance": {
                              "type": "integer"
                            }
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "data": [
                      {
                        "id": "417f51e810c19729de860ea",
                        "date": {
                          "day": 2,
                          "month": "january",
                          "year": 2008
                        },
                        "transactionType": "credit",
                        "category": "507f191e810c19729de860ea",
                        "comment": "40 litres of diesel",
                        "amount": 45,
                        "balance": 90
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "No such user's collection"
          }
        }
      },
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "Create new transaction",
        "parameters": [
          {
            "name": "Authorization",
            "description": "Token issued to a current user",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "date": {
                    "type": "object",
                    "properties": {
                      "day": {
                        "type": "number",
                        "minimum": 1,
                        "maximum": 31
                      },
                      "month": {
                        "type": "string",
                        "enum": [
                          "january",
                          "february",
                          "march",
                          "april",
                          "may",
                          "june",
                          "july",
                          "august",
                          "september",
                          "october",
                          "november",
                          "december"
                        ]
                      },
                      "year": {
                        "type": "number",
                        "minimum": 1900
                      }
                    }
                  },
                  "transactionType": {
                    "type": "string",
                    "enum": [
                      "credit",
                      "debit"
                    ]
                  },
                  "categoryId": {
                    "type": "string",
                    "required": true
                  },
                  "comment": {
                    "type": "string"
                  },
                  "amount": {
                    "type": "integer",
                    "required": true,
                    "minimum": 0
                  }
                },
                "example": {
                  "date": {
                    "day": 2,
                    "month": "january",
                    "year": 2008
                  },
                  "transactionType": "credit",
                  "categoryId": "507f191e810c19729de860ea",
                  "comment": "40 litres of diesel",
                  "amount": 45
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Transaction created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "properties": {
                        "date": {
                          "type": "object",
                          "properties": {
                            "day": {
                              "type": "number",
                              "minimum": 1,
                              "maximum": 31
                            },
                            "month": {
                              "type": "string",
                              "enum": [
                                "january",
                                "february",
                                "march",
                                "april",
                                "may",
                                "june",
                                "july",
                                "august",
                                "september",
                                "october",
                                "november",
                                "december"
                              ]
                            },
                            "year": {
                              "type": "number",
                              "minimum": 1900
                            }
                          }
                        },
                        "id": {
                          "type": "string"
                        },
                        "transactionType": {
                          "type": "string",
                          "enum": [
                            "credit",
                            "debit"
                          ]
                        },
                        "categoryId": {
                          "type": "string",
                          "required": true
                        },
                        "comment": {
                          "type": "string"
                        },
                        "amount": {
                          "type": "integer",
                          "required": true,
                          "minimum": 0
                        },
                        "balance": {
                          "type": "integer"
                        }
                      }
                    }
                  },
                  "example": {
                    "data": {
                      "date": {
                        "day": 2,
                        "month": "january",
                        "year": 2008
                      },
                      "id": "697f191e810c13978de860ea",
                      "transactionType": "credit",
                      "categoryId": "507f191e810c19729de860ea",
                      "comment": "40 litres of diesel",
                      "amount": 45,
                      "balance": 9000
                    }
                  }
                }
              }
            },
            "400": {
              "description": "Validation error",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "properties": {
                      "message": {
                        "type": "string"
                      }
                    },
                    "example": {
                      "message": "validation error message"
                    }
                  }
                }
              }
            },
            "401": {
              "description": "Unauthorized"
            },
            "404": {
              "description": "User not found"
            }
          }
        }
      }
    },
    "/transactions/filter": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "Get all user's transactions",
        "parameters": [
          {
            "name": "Authorization",
            "description": "Token issued to a current user",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "year",
            "description": "Transactions filtered by year",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "month",
            "description": "Transactions filtered by month",
            "in": "query",
            "required": false,
            "minimum": 1,
            "maximum": 12,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Users' transactions' sum by category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "properties": {
                        "category": {
                          "type": "object",
                          "properties": {
                            "categoryId": {
                              "type": "string"
                            },
                            "amount": {
                              "type": "integer"
                            }
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "data": [
                      {
                        "categoryId": "417f51e810c19729de860ea",
                        "amount": 2400
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "No such user's collection"
          }
        }
      }
    },
    "/transactions/categories": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "description": "Token issued to a current user",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "summary": "Get all transactions' categories",
        "responses": {
          "200": {
            "description": "Transactions' categories' array",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "example": {
                    "data": [
                      {
                        "id": "65kf67fdf6f66ff6ffl4",
                        "name": "Groceries"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Transaction": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "A unique id generated by backend"
          },
          "owner": {
            "type": "string",
            "description": "Owners id"
          },
          "category": {
            "type": "string",
            "description": "Category id"
          },
          "date": {
            "type": "object",
            "properties": {
              "day": {
                "type": "integer"
              },
              "month": {
                "type": "string",
                "enum": [
                  "january",
                  "february",
                  "march",
                  "april",
                  "may",
                  "june",
                  "july",
                  "august",
                  "september",
                  "october",
                  "november",
                  "december"
                ]
              },
              "year": {
                "type": "integer"
              }
            }
          },
          "transactionType": {
            "type": "string",
            "enum": [
              "credit",
              "debit"
            ]
          },
          "comment": {
            "type": "string"
          },
          "amount": {
            "type": "integer"
          },
          "balanceAfter": {
            "type": "integer"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "A unique id generated by backend"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "balance": {
            "type": "integer"
          }
        }
      },
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        }
      }
    }
  }
}